# apimatic_calculator
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticCalculator
  # Possible operators are sum, subtract, multiply, divide
  class OperationTypeEnum
    OPERATION_TYPE_ENUM = [
      # Represents the sum operator
      SUM = 'SUM'.freeze,

      # Represents the subtract operator
      SUBTRACT = 'SUBTRACT'.freeze,

      # Represents the multiply operator
      MULTIPLY = 'MULTIPLY'.freeze,

      # Represents the divide operator
      DIVIDE = 'DIVIDE'.freeze
    ].freeze
  end
end
